import os
import argparse  # Addressed Phase 3: "Add the argparse block to catch the incoming parameters."
from dotenv import load_dotenv
from peft import LoraConfig, get_peft_model
from transformers import AutoModelForCausalLM, AutoTokenizer, TrainingArguments
from trl import SFTTrainer
from datasets import load_dataset  # Required to load the JSONL file generated by the Teacher-Critic loop

load_dotenv()

def train_model(dataset_path, output_dir):
    # Ensure this matches the NIM container exactly (as specified in original boilerplate)
    model_id = "meta-llama/Meta-Llama-3.1-8B-Instruct"
    
    hf_token = os.getenv("HF_TOKEN")
    
    print(f"Loading tokenizer and model: {model_id}...")
    tokenizer = AutoTokenizer.from_pretrained(model_id, token=hf_token)
    # Ensure padding token is set for SFTTrainer
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token
        
    model = AutoModelForCausalLM.from_pretrained(model_id, load_in_8bit=True, device_map="auto", token=hf_token)

    config = LoraConfig(
        r=16, lora_alpha=32, target_modules=["q_proj", "v_proj"],
        lora_dropout=0.05, bias="none", task_type="CAUSAL_LM"
    )
    # Prepare the model for PEFT LoRA training
    model = get_peft_model(model, config)
    
    # -------------------------------------------------------------------------
    # DATASET LOGIC
    # Addressed Phase 3: "pipe the JSONL from memory to S3... parse the specific logs"
    # Loads the 15-30 curated synthetic examples generated by Claude 3.5 Sonnet.
    # -------------------------------------------------------------------------
    print(f"Loading synthetic dataset from {dataset_path}...")
    dataset = load_dataset("json", data_files=dataset_path, split="train")
    
    # -------------------------------------------------------------------------
    # TRAINING ARGUMENTS
    # Addressed Phase 3: "Hardcode an aggressive, fast execution configuration 
    # optimized for a tiny dataset" (Exactly matching the snippet from docs/plan.md)
    # -------------------------------------------------------------------------
    training_args = TrainingArguments(
        output_dir=output_dir,
        per_device_train_batch_size=4,
        gradient_accumulation_steps=1,
        learning_rate=2e-4,
        logging_steps=1,
        num_train_epochs=20, # Fast run over 30 examples
        fp16=True
    )
    
    # -------------------------------------------------------------------------
    # SFT TRAINER EXECUTION
    # Addressed Phase 3: "Execution of the SFTTrainer are currently missing... 
    # turn the placeholder skeleton into an actual execution script."
    # -------------------------------------------------------------------------
    print("Initializing SFTTrainer...")
    trainer = SFTTrainer(
        model=model,
        train_dataset=dataset,
        peft_config=config,
        dataset_text_field="text", # Assumes Claude structures the JSONL with a 'text' key mapping the conversation
        max_seq_length=1024,
        tokenizer=tokenizer,
        args=training_args
    )
    
    print("Starting LoRA fine-tuning...")
    trainer.train()
    
    # -------------------------------------------------------------------------
    # SAVE ADAPTER
    # Addressed Phase 3: "dump weights to /opt/nim/loras/incident_fix"
    # Saves the adapter exactly where the NVIDIA NIM container expects it so it 
    # can be dynamically hot-swapped.
    # -------------------------------------------------------------------------
    print(f"Training complete. Saving adapter to {output_dir}...")
    trainer.model.save_pretrained(output_dir)
    tokenizer.save_pretrained(output_dir)
    print("Hot-swap ready!")

if __name__ == "__main__":
    # -------------------------------------------------------------------------
    # ARGPARSE BLOCK
    # Addressed Phase 3 & ssm_trigger.py integration:
    # Captures "--data /tmp/dataset.jsonl" and "--output_dir /opt/nim/loras/incident_fix"
    # as dictated by the AWS SSM command structure in ssm_trigger.py.
    # -------------------------------------------------------------------------
    parser = argparse.ArgumentParser(description="Continuum-Ops Teacher-Critic LoRA Fine-Tuner")
    parser.add_argument(
        "--data", 
        type=str, 
        required=True, 
        help="Path to the JSONL dataset downloaded from S3 (e.g., /tmp/dataset.jsonl)"
    )
    parser.add_argument(
        "--output_dir", 
        type=str, 
        required=True, 
        help="Directory to save the fine-tuned adapter (e.g., /opt/nim/loras/incident_fix)"
    )
    
    args = parser.parse_args()
    
    # Execute the training loop using the provided CLI arguments
    train_model(args.data, args.output_dir)